-- First, let's create the CUBS stream and remove CRANES
UPDATE streams SET name = 'CUBS', id = 'P4-CUBS' WHERE id = 'P4-CRANES';

-- Update all students currently in P4-CRANES to P4-CUBS temporarily
UPDATE students SET stream_id = 'P4-CUBS' WHERE stream_id = 'P4-CRANES';

-- Now update student stream assignments based on the provided lists
-- CUBS stream (54 students)
UPDATE students SET stream_id = 'P4-CUBS' WHERE name IN (
  'NDUMWAMI SOLOMON', 'NANYONJO PATIENCE', 'MUNEZERO BLESSEN', 'AMPUMUZA ELIANAH', 'KIBUDDE MICHEAL',
  'HANNAH KIZITO FRIEND', 'NALUGO CHLOE PRECIOUS', 'ASIIMWE RUJOKI DERRICK', 'NAMUYANJA NAKAWUNGU CARLTON',
  'LUMU FAVOUR ANGEL', 'KYALIGONZA TUSIME JOSEPHINE', 'KISENYI MAGGIE MELLISA', 'KIMBUGWE STEWART',
  'KAYONGO NAMBALIRWA HYRAT', 'NAKIMULI GRACE ETHEL', 'SSENKAAYI NILL EVERISTO', 'AGABA WALTER JOHN',
  'JAKIRA FLAVOUR ROBIN', 'KITENDA ZURI ALMAH', 'NSUBUGA JORDAN MICHEAL', 'NANYONGA LUYIGA ZIADAH',
  'KAWUKI GIPSON', 'SSALI MICHEAL', 'SSENDYOSE CYRUS FRANKLIN', 'BYAMUKAMA KEITH',
  'WANYENZE MARIANAH TATIANAH', 'NAMUBIRU MULASANGEYE REGINA', 'LUGENDO AMOS', 'NAMIREMBE NICOLE MARIA',
  'NGELESE HOSANAH VALERIA', 'NATASHA OKALLO ESTHER', 'YIGA SEBASTIAN TRAVIS', 'NASSIWA HAILEY ULRIKA',
  'KIMERA JONATHAN', 'SSENYONJO MERCY', 'NAMBALIRWA TRUDE ABIGAIL', 'NSIIMIRE FAITH', 'NAKANWAGI KEIRAH',
  'NAMAASA MUKIRYA AMRON', 'SSEREMBA JEREMIAH', 'ATWIINE JOTHAM', 'MAGOMA CHARLES BENHUR',
  'NAMUMBEJJA RYHAN', 'ASINGUZA BRENDA', 'SSENYONGA JEREMIAH', 'KOBUSINGE MARIANAH NATAL',
  'NAYEBARE TIMOTHY', 'KASULE ZAWADIELSEN E', 'ATUHIRE JOSEPHINE', 'MWIMA RAIHAN', 'LUKWAGO RAYAN F',
  'KARUNGI NEIRAH IN', 'BATANDA DYLAN', 'LUBOWA ABUBAKER'
) AND class_id = 'P4';

-- EAGLETS stream (44 students)
UPDATE students SET stream_id = 'P4-EAGLETS' WHERE name IN (
  'NAKIBONEKA PRUDENCE', 'SINGOMA EDGAR', 'MUKISA FAVOR', 'KEEYA MALCOM', 'KAWEESI EVANS', 'KASIITA OMAR',
  'LUBEGA MICHEAL MULUNGI', 'LWASSA DALTON ELIJAH', 'DDUMBA JORAM', 'IRWA ALLE IAN', 'MUKISA TRAJAN ANDREWZ',
  'NAKASIISA SHEILLA KABOGGOZA', 'MUWAMBA WILFRED', 'BUGEMBE SHAKUR DDUMBA', 'NAKALANZI PROMISE',
  'NAKIGULI SHIVAN', 'SSERUYANGE TIMOTHY', 'KYEYUNE DANIEL', 'BUKENYA NOEL KRYSTAL', 'MAGALA DALTON EDWARD',
  'KISIRA JORDAN', 'WALUSIMBI JETHRO VALENTINE', 'MUKIIBI JONATHAN', 'NAMBEJJA CHRISTINE',
  'AKAMPURIRA CALVIN', 'WAIKYA ISRAELLA PHOENIX', 'NAMYALO TASHEEMIM', 'KAGIMU SHEMAIAH GOODLUCK',
  'NKWISANA REAGAN', 'NASIMBWA NANA CIARA', 'MUKULU MAHAD NASSIB', 'KAFEERO ELIJAH PASCAL',
  'ANKUNDA DONALD', 'NASASIRA DIVINE', 'TUMUSIIME FRANCIS', 'KAKINDA FABIAN', 'NANTEZA LYAN',
  'KAWEESI ABDULSHAKUR', 'MIGADDE SHAKUR SUCCESS', 'NAMUYIGA JOVIA', 'NABUKEERA SHUKRAN',
  'SSIMBWA TALIQ', 'BYARUHANGA ASHNAZ', 'SEKATE GODFREY'
) AND class_id = 'P4';

-- P4 SPARKLES stream (52 students)
UPDATE students SET stream_id = 'P4-SPARKLES' WHERE name IN (
  'AGABA JOHN TREASURE', 'AKATUHEREZA WILLISHA MERRICK', 'AMILAH ADAMS KYEYUNE', 'ARIIHO ISRAEL',
  'JARINDA MARTHA ELLONY', 'ARINITWE CLEIN', 'BALIKUDDEMBE ELVIS', 'BARUNGI VICTORIA', 'BESIGYE TRICIA',
  'BUWEMBO NEYMAR JUNIOR', 'BUYONDO ISRAEL', 'BWIRE CHLOE BRIGHTON', 'BWIRE EMMANUEL',
  'ISHIMWE QUEEN NGABIRE', 'ISIKOT VERON JOY', 'KAITESILEA', 'KALIBBALA AKRAM', 'KALYANGO RAHEEM',
  'KAMUGISHA GIOVANA', 'KATUNDA DARREN', 'KAVUMA NORINE ESTHER', 'KAWEESA KIERAN',
  'KAWEESI HASHIM SSESAAZI', 'KIBUDDE NICHOLAS', 'KIGULI NAILOR', 'KYOMUHENDO GRACE KIBIRIGE',
  'LUTAAYA CATHERINE', 'LWALANDA HAKIM', 'MAGUMBA SHAKIR', 'MAYANJA VUUBI', 'MPAIRWE SERENE LYTON',
  'MUBINZI MOSES', 'MUGABI JOSH MICHEAL', 'NAKABUYE CYNTHIA', 'NAKALUNGI GABRIELLA IVANNAH',
  'NAKISIGE PRECIOUS SHALOM', 'NAKITTO RHONEL RUTH', 'NAMAGALA EDRON JOAN', 'NAMPIIMA PAULINE',
  'NAMUBIRU AFRICA RACHEAL', 'NAMUJJUZI WINFRED', 'NANJEGO VICTORIA', 'NANKUBUGE SHAINAH',
  'NANSUBUGA TRACY CAMILLA', 'NANYONJO AGNES', 'NANYUNJA RINAH NANA', 'NDAGIRE SARAH',
  'NIYIBIZI JERUSA', 'OLA KERON MICHELLE', 'RASHMY WAHIDAH IMAN', 'SEKATE NOELLA', 'SSEKAJJA NA'
) AND class_id = 'P4';

-- P4 BUNNIES stream (51 students)
UPDATE students SET stream_id = 'P4-BUNNIES' WHERE name IN (
  'NASIRUMBI ISABELLA', 'NALUBEGA MARIA', 'MALAIKA TRIXIE KIYAGA', 'AHUMUZA PRAISE ROBERT',
  'KATUMBA MARIA', 'AKWERO LYN AUSTINE', 'WASSWA KABUYE JONATHAN', 'MUKIRIZA GEORGE MBOOWA',
  'MIREMBE RAUDAH', 'KATUMBA CONRAD', 'NAMAZZI DESIRE HILDA', 'NABBONGOLE KATRINAH',
  'SANYU NISHA GASARO', 'NTAMBI REAGAN', 'MUYAMA ABIGAIL', 'AKAMUTUHA JANET',
  'IRENE MALAIKA NABBAALE', 'KOMUJUNI FEDRACE', 'NYAKATO EDRINA', 'NALWANGA JAZMINE',
  'WODERO JOSHUA', 'NALUYANGE MADRINE DOROTHY', 'TAMALE JOHN FRANCIS', 'MUSIIME GIFT',
  'SSEWANYANA AARON', 'NANSUMBI DEBORAH KENDRA', 'NAMANDA MAJORINE', 'AINEMBABAZI MELLISA',
  'ATUHAIRE GEORGIA RANIA', 'ANVIKO SHANTAL MARION', 'KAKUNGULU RYAN MARK', 'NABUKENYA JOSEPHINE KATE',
  'WALUSIMBI MARTIN', 'NAMUGERWA SABRINA', 'NAMAGANDA BRIANNAH STEPHANIA', 'SSEMPIJJA OSCAR',
  'MULUNGI ASABA JOANNAH', 'KIMBUGWE ABDALLAH', 'ELOY TITUS SSENTONGO', 'AINEMBABAZI GRACE REINAH',
  'TREASURE ELIZABETH SEKU', 'BATANDA JETHRO', 'MAGOMA BELICIA ELIZABETH', 'KWEZI ROBIN',
  'KATO JOVANS KABUYE', 'NAMULI COMFORT', 'NAKASUMBA ANITAH', 'TUKUNDANE EUGENE SHIFU',
  'SSERUMAGA PUTIN TREVIS', 'TURYAKIRA TYRONE JUNIOR', 'KAVUMA AMIR'
) AND class_id = 'P4';