-- First, create all classes if they don't exist
INSERT INTO public.classes (name) VALUES 
  ('P1'), ('P2'), ('P3'), ('P4'), ('P5'), ('P6'), ('P7')
ON CONFLICT (name) DO NOTHING;

-- Get class IDs
WITH class_ids AS (
  SELECT id, name FROM public.classes WHERE name IN ('P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7')
)

-- Insert streams for each class
INSERT INTO public.streams (name, class_id)
SELECT stream_name, class_id FROM (
  -- P1 streams
  SELECT 'DIAMONDS' as stream_name, id as class_id FROM class_ids WHERE name = 'P1'
  UNION ALL
  SELECT 'PEARLS', id FROM class_ids WHERE name = 'P1'
  UNION ALL
  SELECT 'STARS', id FROM class_ids WHERE name = 'P1'
  UNION ALL
  -- P2 streams
  SELECT 'GOLDEN', id FROM class_ids WHERE name = 'P2'
  UNION ALL
  SELECT 'KITES', id FROM class_ids WHERE name = 'P2'
  UNION ALL
  SELECT 'MARIGOLD', id FROM class_ids WHERE name = 'P2'
  UNION ALL
  -- P3 streams
  SELECT 'CRANES', id FROM class_ids WHERE name = 'P3'
  UNION ALL
  SELECT 'PARROTS', id FROM class_ids WHERE name = 'P3'
  UNION ALL
  SELECT 'SPARROWS', id FROM class_ids WHERE name = 'P3'
  UNION ALL
  -- P4 streams
  SELECT 'EAGLETS', id FROM class_ids WHERE name = 'P4'
  UNION ALL
  SELECT 'BUNNIES', id FROM class_ids WHERE name = 'P4'
  UNION ALL
  -- P5 streams
  SELECT 'SKYHIGH', id FROM class_ids WHERE name = 'P5'
  UNION ALL
  SELECT 'SUNRISE', id FROM class_ids WHERE name = 'P5'
  UNION ALL
  SELECT 'SUNSET', id FROM class_ids WHERE name = 'P5'
  UNION ALL
  -- P6 streams
  SELECT 'RADIANT', id FROM class_ids WHERE name = 'P6'
  UNION ALL
  SELECT 'VIBRANT', id FROM class_ids WHERE name = 'P6'
  UNION ALL
  SELECT 'VICTORS', id FROM class_ids WHERE name = 'P6'
  UNION ALL
  -- P7 streams
  SELECT 'ACHIEVERS', id FROM class_ids WHERE name = 'P7'
  UNION ALL
  SELECT 'SUCCESS', id FROM class_ids WHERE name = 'P7'
  UNION ALL
  SELECT 'WINNERS', id FROM class_ids WHERE name = 'P7'
) as stream_data
ON CONFLICT (name, class_id) DO NOTHING;

-- Now insert all students
-- P1 DIAMONDS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ADITE DEMI'), ('ALINDA JAMES ALVIN'), ('AMARO JEMIMAH GRACIOUS'), ('ARINITWE ESTHER'),
  ('ASANTE MARTHA KIRABO'), ('ATATI JOSHUA ELVIS'), ('BWIRE ELIJAH'), ('BYAKATONDA TATIANA'),
  ('HAALAH MULUNGI NABAWANUKA'), ('INEEZA NORAH NGIRISOKO'), ('ISAAC JEZREEL SSEBUGWAWO'),
  ('JOY BERNICE BIACA'), ('KABUUBI ERAN EARL'), ('KATEREGGA RIDHIWAN'), ('KAYEMBA JAMES RAYMOND'),
  ('KAYUMBI GADI'), ('KEMIREMBE ELYN'), ('KHALAYI JOY NAMBAFU'), ('KHIISA KRISTY SHILOH'),
  ('KIGGUNDU JORDAN WASSWA'), ('KIGOZI MALCOM GOLD'), ('KOBUSINGE IVY'), ('KYOMUGISHA DENISE'),
  ('LUMU GABRIEL KIGONGO'), ('MALE IBRAHIM'), ('MARIA NOELLA LUSWATA'), ('MATOVU ELISHA'),
  ('MIREMBE ARIANA'), ('MUBIRU RAHIM'), ('MUHATSI DYLAN SKYLER'), ('MUTAMBA KELLY KATOOKWA'),
  ('MUYONDO ALI SEIF'), ('NABASA TREASURE'), ('NAJJEMBA SHALOM KABOGGOZA'), ('NAKAKANDE ABIGAIL JOSEPHINE'),
  ('NAKALANZI SAUDAH'), ('NAKAWOMBE SHAMUSAH'), ('NAKAWOOYA MAE'), ('NAKIMERA LATIFAH'),
  ('NALUKENGE IRENE GRACE'), ('NALUZZE FAHIMA'), ('NAMAGEMBE TRISHINAH'), ('NAMBAALE NOREEN'),
  ('NAMBEJJA HAURAH'), ('NAMPIJJA SHERINE'), ('NAMUGGA DENISE TENDO'), ('NAMULONDO JOSEPHINE MARIA'),
  ('NAMWANJE CHRISTINE'), ('NANYANZI JOERIN RUTH'), ('NASSALI DIVINE MERCY'), ('NASSOZI ASHLEY'),
  ('NAZZIWA SHAKIRA'), ('NSUBUGA CHRISTIAN'), ('NSUBUGA EVRA KATOSI'), ('OWORI MICHAEL'),
  ('RAMON DANIEL JJUNJU'), ('SSEBALE ABDUL ASAD'), ('SSEMPIJJA GRIFFIN'), ('TALEMWA MWESIGE'),
  ('TEKULI BERNICE VICTORIA'), ('TROY ISRAEL KIYAGA'), ('TUMUSIIME SAMUEL ELLIS'), ('WASSWA BERNAZIL RAYAN')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P1' AND s.name = 'DIAMONDS' AND s.class_id = c.id;

-- P1 PEARLS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABEINE MARK'), ('AHEREZA ELIJAH'), ('AINEMBABAZI GIANNA'), ('AMPULIRE RAHMAH'),
  ('ANKUNDA EDMUND'), ('ANKUNDA PRAISE'), ('APIO SHAYLAH AINE'), ('BATANDA CALISTA'),
  ('BIYINZIKA JOSIAH KIMERA'), ('CARLTON JEREMIAH LUTAAYA'), ('CHAR GAI ALIER NHIAL'),
  ('DDUMBA ABDUL SHAMIR'), ('ELOY TROY TEFFANE SSENTONGO'), ('KAKOOZA MAYSON'), ('KALEMBE NIKITA'),
  ('KALYOWA FARAJ'), ('KANYANA AKIM'), ('KATEREGGA HARRISON MIGUEL'), ('KATONGOLE SHAKUR'),
  ('KAWOLO EMMANUELLA PRECIOUS'), ('KAWUMA SHAWN DYLAN'), ('KIRSTEN JOY KIZITO'), ('KIYINDIRU HUMPHERY .K.'),
  ('KUTEESA GLORY NABULYA'), ('KWAGALA DESTINY'), ('LUBOWA SHIFRAH NAMWANJE'), ('LUYIGA TAHIRAH FAVOUR'),
  ('MARWA GRIFFIN'), ('MPAIRWE RODNEY LUTHER'), ('MULUNGI NOAH ELIJAH'), ('MURUNGI PRECIOUS ARIANA'),
  ('MUSINGUZI LAURIAN'), ('NABIRYE JAEL AYEBALE'), ('NABULYA BRENDA'), ('NAKANWAGI SHAMIM'),
  ('NALUGWA HANNAH KRISTA'), ('NAMATOVU JESCA'), ('NAMIRIMU JOANAH AMARAH'), ('NAMUBUYA BEATRICE CLARISHA'),
  ('NAMUGERWA ESTHER'), ('NAMUKWAYA RHORITAH'), ('NSUBUGA IQRA'), ('NTONGO JANEFRANCIS SSALI'),
  ('OLOYA MYLES LAUREN'), ('PRINCE KAMUKAMA DAVID'), ('RAPHAEL MIC PIDO'), ('RUGANYIRWA EISHA MARIAM'),
  ('SEKATE JOSEPH JUNIOR'), ('SEKITO KAYAN ISRAEL'), ('SHADRACK LIAM KAZIBWE'), ('SHAHEEM ASHRAF HATTE'),
  ('SSALI ANWAL'), ('SSEKANDI JOSEPH'), ('SSEMAGANDA AIMAN'), ('SSEMPIJJA LUCKY DALTON'),
  ('SSENTONGO JOEL EMMANUEL'), ('TAHIRAH ABUBA KAMISHA'), ('TASHINAH ABUBA HAKASHA'), ('TEBUSWEKE GABRIEL ASONYIWA'),
  ('TUMUSIIME KERON GABRIEL'), ('TUMWEBAZE BURNET'), ('VALEREEN OGWANG'), ('WALULYA CHARLES EZRA'),
  ('WAMALA CUTHBERT MELVIN')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P1' AND s.name = 'PEARLS' AND s.class_id = c.id;

-- P1 STARS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AHWERA LIANE'), ('AKANJUNA MIRACLE'), ('AKANYIJUKA ADAM'), ('AKUNZIRE ARIANA'),
  ('ALBA EITU'), ('ALINDA KAREN JOY'), ('AMANYA DALLEN PLASID'), ('AMWINE KATRINAH'),
  ('ANKUNDA AUDRINE NYANGOMA'), ('ARUBE KAMILA'), ('ASABA ISAIAH BRIGHTON'), ('ATUNGOZA IVANA'),
  ('ATWIINE KEYAAN KABYANGA'), ('BATANDA JEZREEL AVIEL'), ('BIRABWA ANNAMARRE BELINA'), ('BUSINGE KYLIAN ALPHA'),
  ('BWIRE KLEIN GOODLUCK'), ('DDUNGU JORAN REYNOLD KAKONA'), ('HUZAIFAH MOHAMMED'), ('JJINGO GARVIN IAN'),
  ('KABATEESI THEREASA KISAKYAMARIA'), ('KAGERE MALHA MARTHA'), ('KALUNGI DYLAN ALPHA ABEL'), ('KASIBANTE WALLACE MICAH'),
  ('KATEREGGA ETAN RIDSON'), ('KATO ALDRINE'), ('KAZIBWE EMMANUELLA'), ('KEBIRUNGI MARY BENICE'),
  ('KEZA CANTRELL'), ('KIGGUNDU JOEL'), ('KIKOMEKO RODNEY'), ('KINTU VIVAN AUSTIN'),
  ('KIRABO TRINITY'), ('LUBUULWA PETER'), ('LULIIKA AARON ROMANS'), ('MAGEZI MESHACH'),
  ('MANZI TREASURE PETER'), ('MAYANJA ADRIAN'), ('MAYIGA RODRICK'), ('MIGADDE ETHAN BLANE MARK'),
  ('MIREMBE CRYSTAL MELAN'), ('MULINDWA ELVINE DAREEN'), ('MUSINGUZI DEBORAH CELIA'), ('MUTHARIMI GRACE MUTEMBEI'),
  ('MUWANGA HAIZA AADIFA'), ('MUWANGUZI ISAIAH'), ('MUYINZA GABRIELLA JEANILER'), ('MWINGANIZA CONRADE'),
  ('NAKABIRI ZION KAYEMBA'), ('NAKABUUBI ELENA SKYLAR'), ('NAKAJIRI MARIA GORRET'), ('NAKAWOOYA GLADYS'),
  ('NAKITENDE KEISHA'), ('NAMUMBYA KEVINA QUEEN'), ('NASSANGA JOSELYNE REGINA'), ('NATUKUNDA MARTHA KAYLA'),
  ('NEZA JESSE MUVARA'), ('NGABO EMMANUEL'), ('SSEBATA HEZRON CYRIAN'), ('SSEMAKULA JEZREEL'),
  ('SSENOGA ISAIAH'), ('SSENTABA JORDAN'), ('TAAKA ABBA BATHESHEBA'), ('ZALWANGA AMIRAH')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P1' AND s.name = 'STARS' AND s.class_id = c.id;

-- P2 GOLDEN
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABAHO FIACRE EUGENE'), ('ADIL KIVIIRI MITTI'), ('AGASHA ABIGAIL'), ('AHURIRE JONATHAN'),
  ('AINEBYONA GABRIELLA ALINDA'), ('AKAMPULIRA ARISTARCHUS SAMUEL'), ('ALUMA AARON'), ('ASHABA ABIGAIL CHLOE'),
  ('ATUKUNDA SALOME'), ('AYONGYERAHO SAMANTHA'), ('BUKENYA POWEL JUNIOR'), ('BYAMUKAMA MULUNGI RHODAH'),
  ('GANZA HOLLY SHAK'), ('GITTA JAMAL'), ('HIRWA TETA HUGUETTE'), ('JJUUKO DRAKE PUIS'),
  ('KABUYAYA SHANNA'), ('KATO JESSE'), ('KATUMBA WALLACE MUGERWA'), ('KAYANJA DALTON'),
  ('KIJJAMBU GRACE'), ('KIRENDA HAVANS KERAMO'), ('KISAKYE ELIANA TENDO'), ('KISITU TREVIS STEVEN'),
  ('KITENDA GIAN MUKIRIZA'), ('KIYAGA HADIJAH'), ('KUBAGYE ISAIAH'), ('KUNDHUBA LEVITICUS MIGUEL'),
  ('KWAGALA GRAHAM'), ('LUBOWA ABDUL KARIM'), ('LUTAAYA JORDIN SAAVA'), ('LWASA DAVIS'),
  ('MAGUMBA SHAMYRAH'), ('MAWEJJE EXPERITO'), ('MAYANJA FABIAN VANVAN'), ('MBOGGA JOEL'),
  ('MIREMBE LUCY FLAVIA'), ('MUHOZA PRAISE'), ('MUSIITWA MARCUS FRANCIS'), ('MUWANGA HAIMA AADIHA'),
  ('MUWANGUZI CHRIS DANIEL'), ('MWEBIGWA ELIJAH'), ('NAJJUUKO NALUZZI'), ('NAKAAYI ABIGAIL'),
  ('NALUJJA TIMAYA'), ('NAMULINDWA MIRACLE'), ('NANKYINGA SHANNEL MARIA'), ('NASSALI BASHIRAH JOY'),
  ('NATUHWERA ABIGAIL KATONGOLE'), ('NAZZIWA ELIANA GRACE'), ('NUWASIIMA ELIJAH JUNIOR'), ('RUGABA CAESER'),
  ('SSEBBUMBA ISAAC IQRAM'), ('SSEGAWA JORAM'), ('TIBANYAGA GENESIS'), ('ZAWEDDE NADRA')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P2' AND s.name = 'GOLDEN' AND s.class_id = c.id;

-- P2 KITES
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AGUTI MATINA'), ('AKATUKUNDA TRIUMPHANT'), ('AMIR ADAMS KYEYUNE'), ('ATUHURA TRISHA LINATE'),
  ('ATULINDA CLARA MERISHA'), ('BALAM EDITH LUGOJA'), ('CYOGERE JAYDEN MUVARA'), ('EKYE AKMAL PRICELESS'),
  ('EKYE KAMAL'), ('KABAGAMBE SPEEDMAN JESUS'), ('KALULE CATHERINE VANNAH'), ('KHIISA PETRONELLA'),
  ('KIRUNDA EMMANUEL KWAME'), ('LAKER LIZETH'), ('LUMU DAGLOUS LUCKY'), ('LUSIBA JONAH'),
  ('LUTAAYA JOHN WYCLIFF'), ('LUZINDA ELIJAH KISAKYE'), ('MUGAMBE TYRONE'), ('MUGARURA SHAROT'),
  ('MUHUMUZA NEWTON'), ('MUKISA TREASURE'), ('MULUMBA MELISSA MICHELLE'), ('MULUNGI MACKYLA'),
  ('MUYOMBA PAMELLA'), ('NABAALE MARIA MACKEILA'), ('NABATANZI BLESSING'), ('NABATANZI MARIA'),
  ('NABAYEGO MARTHA ARIANA'), ('NABUKEERA MARTHA BETTY'), ('NABUMBO BEATRICE'), ('NAGADYA WENDYWEEKS'),
  ('NAKALINZI VICTORIA NABBIMBA'), ('NAKAYIWA BLESSING'), ('NAKIGUDDE JESCA'), ('NALWADDA MARIANAH'),
  ('NAMAGANDA MARY MUBEEZI'), ('NAMAGEMBE ABIGAIL KIRABILA'), ('NAMATA PRISCILLA SHALOM'), ('NAMBUUSI FIRIDAUS'),
  ('NAMBUUSI VERONICA NAKATO'), ('NANSUBUGA KELSIE'), ('NANTIMBA JULIAN SEKATE'), ('NASSANGA RIDAH BASINGA'),
  ('NENDEJYE MARION'), ('NGOGE VIVIAN'), ('OPI HIRAM ANISON'), ('RABEIA ABDALLAH HAMED'),
  ('SSEGAWA CLYDE LARKIN'), ('SSEGUJJA DAVASHA LOVE'), ('SSENTONGO JEMIMAH PRECIOUS'), ('YAWE AMBER HADIA')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P2' AND s.name = 'KITES' AND s.class_id = c.id;

-- P2 MARIGOLD
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABIGABA MATTHEW'), ('ABIGARURAHO SPLENDID'), ('ACHOLA SAMANTHA'), ('AHIMBISIBWE JEREMIAH'),
  ('AHIMBISIBWE KEVIN'), ('ALIGUMA EMILLY'), ('ALINDA TIFFANY'), ('ANZOA FAITH'),
  ('ATAI KAYLAH ARINDA'), ('ATUHAIRE TRACY KARUNGI'), ('ATUHIRE ANNA MARY LORETTA'), ('BIRUNGI KIMORA'),
  ('BYARUHANGA TRACY'), ('KAGIMU JESHAIAH MELODY'), ('KANYI MPAKANYE MAURICE'), ('KASIRYE BADURIAH'),
  ('KASOZI CYRUS MUBIRU'), ('KAVUMA LIBERTY'), ('KIGGUNDU FRANCIS EXAVIER'), ('KIGOZI CALVIN'),
  ('KIMBUGWE MUHAMMAD ALI'), ('KIMERA JERICHO'), ('KIMULI ELIJAH'), ('KOBUSINGYE NATALIE'),
  ('KYOBE JOSIAH MULUNGI'), ('LAKICA ABIGAIL CHLOE'), ('MAGUMBA JAHIM'), ('MUGERWA EDRINE'),
  ('MUKISA HAM'), ('MUKISA JEREMIAH'), ('MULUNGI ASHER NTWALI'), ('NABIRYE LAILAT'),
  ('NAKYANZI CHLOE MALAIKA'), ('NAKYEYUNE MARIA DARLEN'), ('NAMIREMBE JUSTINE NATALIA'), ('NAMPIJJA RAHUMAH'),
  ('NAMUKASA CLAIRE'), ('NANTULYA EZRA'), ('NDAGIRE SHANER RANISH'), ('NDAHIRO BRIAN'),
  ('NIWAGABA DIVINE'), ('NTEYERA ABIGAIL ZITA'), ('NYANZI PRESTON'), ('OLA CHRISLEY'),
  ('OMENO MAURICE JUNIOR'), ('ONYIRU JOY ECOKU'), ('OWAMAHORO RAUTHA'), ('SAKA RAHIM SUNDAY'),
  ('SSEKANJAKO TRAVIS VIANNEY'), ('WANDERA GARY JOSIAH'), ('WASSWA JORDAN')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P2' AND s.name = 'MARIGOLD' AND s.class_id = c.id;

-- P3 CRANES
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AINE FLOKI'), ('AINOMUGISHA PURITY'), ('AKANDWANAHO MOBERT'), ('ALOYO JIREH OKOT'),
  ('ALPHA SADIKI'), ('AMODING DORCAS LAURETTA'), ('ANKUNDATRICIA'), ('ANYOLE JAAD GALA'),
  ('ARINAITWE DYLAN GIFT'), ('ARINDA LINDSAY'), ('ARIO VICTORIA PRETTY'), ('ASASIRA PHILLIP PROSPER'),
  ('ASIIMWE ERINAH MERCY'), ('ATUHIARE ELLAH MUHABWE'), ('AYEBALE LUCKY'), ('BAGALA LETICIA KAKYUBYA'),
  ('BBOSA CYRUS RICH'), ('GALABUZI FARHAN'), ('ISHIMWE NGIRISOKO DEBORAH'), ('ITUNGO PHILLIP ROMEO'),
  ('KABUGO ALPHA DICKENS SHINE'), ('KALEMA ELVIS SSEJINJA'), ('KAMYUKA RYAN'), ('KASOZI MOSES DALTON'),
  ('KAWEESI MELVIN'), ('KAZOOBA CHARLES'), ('KIMBUGWE TAPHATH KIRABO'), ('KIYAGA EMMANUEL'),
  ('KOBUSINGE LAURITAH'), ('KWAGALAKWE TRINITY DIVINE'), ('MAGALA VICTOR PRINCE'), ('MARIA IVY LUSWATA'),
  ('MAYIGA FRANCIS'), ('MFURAKOZI ELIZABETH'), ('MUGALU ETHAN MBOWA'), ('MUGANWA GABRIEL ECKOUGHT'),
  ('MUHOZA SOPHIE GIFT'), ('MUTESI FAIZER NAMULONDO'), ('MUWANGUZI CALVIN'), ('MUYOMBA KEVIN'),
  ('NABUTONO PURITY'), ('NAGAWA ELLA ANNA'), ('NAKAJIRI JACKLINE CLARICE'), ('NAKATO BLESSED ABIGAIL'),
  ('NAKAWOOYA DIVINE'), ('NAKAYIZA MILKAH'), ('NAKIBUYE ELIZABETH'), ('NAKIBUYE ERIKA'),
  ('NAKIREMBEKA RUTH TENDO ESTHER'), ('NALUBEGA NELLYN'), ('NAMATOVU ABIGAIL SHANEL'), ('NAMATTA JOSELYN CELYN'),
  ('NAMIGADDE KIRABO SHAMIRAH'), ('NAMIREMBE ELIANAH'), ('NAMULI ADONAI'), ('NANFUKA SYLIVIA'),
  ('NANGOBI FAVOUR RIHANA'), ('NANSAMBA MARTHA MELINA'), ('NDAGIRE GENESIS PERUTH'), ('NGELESE RIAM VIANNY'),
  ('SSAAZI WYNAND RAUBEN'), ('SSEGUYA SHAFIC'), ('SSEKITO MUNIRA'), ('WASSAJJA DICKENS CHARLES'),
  ('WASSOZI CALVIN RASHFORD'), ('WASSWA DOUGLAS')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P3' AND s.name = 'CRANES' AND s.class_id = c.id;

-- P3 PARROTS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ACEN ANNABEL CAISEY'), ('ADAM SAMA MOKHTAR'), ('AGABA JOHN AUSTIN'), ('AKAMPULIRA CATALEYA RUTH'),
  ('ALIMPA DESTINY ANGELLA'), ('AMJAD YASIR KASIRYE'), ('ANYIJUKIRE FAVOUR DOLLARS'), ('ARISHABA ELIJAH KAHANJIRWE'),
  ('ASINGUZA JOLLINE'), ('ATUHAIRE PRAISE CYNTHIA'), ('ATUKUNZIRE SPLENDOR'), ('AWADI BENTI SALAH'),
  ('BAINOMUGISHA ABIDAN'), ('BANADDA HUMAIRAH'), ('BBEMBA SOLOMON DALTON'), ('BUKENYA IMRAN'),
  ('BUSHIRAH HAKIM'), ('DDAMULIRA AMANI KISIRINYA'), ('DDUMBA CANAAN KISAKYE'), ('JOHN KEELY KUTEESA'),
  ('KAZIBA ERIAS'), ('KIRABO KEISHA'), ('KYOBE HEAVENS MACKYLINE'), ('MASSA RAHUMA'),
  ('MATOVU KEITH'), ('MAYIGA SADAT'), ('MUGERWA MARVIN KITIIBWA'), ('MUGISA VALERIE'),
  ('MUGISHA HARVEST'), ('MUHOOZI ABRAHAM'), ('MUKISA BRINAH AISHA'), ('MUKISA SEAN'),
  ('MUKOOTA SHAREN'), ('MUSIBIKA SHAHIDAH'), ('MUTAAWE MARJORINE'), ('NABAGULANYI RHONAH'),
  ('NABUUMA EVELYN'), ('NAGGAYI GLORIA'), ('NAGUJJA MELLISA'), ('NAKACWA SYNTHIA'),
  ('NAKAFEERO CHLOE KATRINAH'), ('NALUGGWA JULIANAH'), ('NALUSOZI MADRINE'), ('NAMBUUSI HASIFA LULE'),
  ('NAMPEEWO RHAUDAH'), ('NAMUDDU JULIET NALUSIBA'), ('NANTEZA JULIAN TENDO'), ('NANYANGE EMMANUELLA'),
  ('NANYUNJA ANGEL MYRA'), ('NASSUUNA ANNA CHLOE'), ('NGABO ETHAN MAZINGA'), ('NINSIIMA MARY MERCY'),
  ('NSUBUGA ETHAN SAMUEL'), ('NYANGOMA MARIANA MELISSA'), ('SANYU LOUIS'), ('SSALI JORDAN'),
  ('SSEKYANZI DAVAN'), ('SSEMWANGA RODNEY'), ('SSEMWOGERERE SADDAM'), ('TUMUHAISE BENJAMIN'),
  ('WODERO JONATHAN')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P3' AND s.name = 'PARROTS' AND s.class_id = c.id;

-- P3 SPARROWS  
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABAASA ALVIN'), ('ABAASA BENJAMIN'), ('ABDUDALLAH AZIZ KIZZA'), ('AGABA RUGABA SOLOMON'),
  ('AIJUKA ELYNET'), ('AINEMABABAZI AMELIA'), ('ALINDA ETHAN'), ('AMORAH BLESSING'),
  ('APIYO ABIGAIL CAIRA'), ('ATWIINE JESSE BYAMUKAMA'), ('BAFUWE JOSIAH SIMON'), ('BAKYAZI ZULPHER'),
  ('BALIRUNO ARTHUR MUWANGUZI'), ('CHIOMAKA NASHIELLY ABIGAIL'), ('EMMANUELLA CON'), ('INEZA CANDICE'),
  ('KABALI NICHOLAS VICENT'), ('KABBALE MARK BERNARD'), ('KAKANDE ROMANS'), ('KALWAZA JAMES AHURIRE'),
  ('KARUNGI PRECIOUS'), ('KASIRYE BASHIRAH'), ('KASOZI TRAVAN MUWONGE'), ('KATENDE DALDAH NAEMU'),
  ('KEMBABAZI ELEXANA'), ('KIGOZI ABDUL SHAKUR'), ('KIRYOWA ALOYSIOUS'), ('KISAKYE PAULINE DELISHA'),
  ('KWAGALA DIVINE SSEBUGUZI'), ('LAGUM NICHOLETTE'), ('LUMU ANDREW'), ('LWANGA SHAFIK BASUDDE'),
  ('MATOVU JOHN HEIDEN'), ('MATOVU MICAH'), ('MBABAZI HILTON MIREMBE'), ('MILLA MIRACLE TIMOTHY'),
  ('MPAIRWE LESLEY LEONAH'), ('MUHUMUZA GRACE MUTONI'), ('MUKAMA LIAM JONATHAN'), ('MUKIIBI VIANNEY'),
  ('MUTONI ELISHEBAH ALISON'), ('MUWONGE LUCKY JONATHAN'), ('NAKIWALA MALAIKA HAZEL'), ('NALUBEGA DINAH'),
  ('NAMBOGO CHRISTABEL'), ('NAMIIRO MONICA CLARA'), ('NAMUGGA VALERIA'), ('NANDAWULA MIRIAM'),
  ('NASSOZI VALORIE BLESSINGS'), ('NDETESHEKO GIFFIN GIDEON'), ('NOKRACH KEYLOR CRUZ'), ('NSHUTI ELISHA'),
  ('NTARE MAURICE NABLE'), ('NUWAGABA AARON SHELDON'), ('NYAKATO MARIA MICHELLE'), ('NYOMBI AMIRA'),
  ('NZIZA ELIJAH'), ('OKOT ADRIEL HISGRACE'), ('OKOTEL EMMANUELLA'), ('OMODING ETHAN EYALAMA'),
  ('ROHAAN BAHAR'), ('SSANGO JOVAN ANGELLO'), ('SSEBUGWAWO JONATHAN KISLEV'), ('TOMUSNAGE KATRINAH'),
  ('WALAKIRA ALOYSIOUS'), ('WALUKAGGA SALIM'), ('WASSWA ABEL BRANDON')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P3' AND s.name = 'SPARROWS' AND s.class_id = c.id;

-- P4 EAGLETS (including DAV placeholders)
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AKAMPURIRA CALVIN'), ('ANKUNDA DONALD'), ('BESIGYE TRICIA'), ('BUGEMBE SHAKUR DDUMBA'),
  ('BUKENYA KRYSTAL NOEL'), ('BWIRE EMMANUEL'), ('BYARUHANGA ASHNAZ'), ('DDUMBA JORAM'),
  ('HIRWA ALLE IAN'), ('ISINGOMA EDGAR'), ('KAFEERO ELIJAH PASCAL'), ('KAGIMU SHEMAIAH GOODLUCK'),
  ('KAITESI LEAH'), ('KAKINDA FABIAN'), ('KAMUGISHA GIOVANA'), ('KASIITA UMARU'),
  ('KAVUMA AMIR'), ('KAWEESI ABDUL SHAKUR'), ('KAWEESI EVANS'), ('KEEYA MALCOM'),
  ('KIBUDDE NICHOLAS'), ('KIGULI NAILOR'), ('KISIRA JORDAN'), ('KYEYUNE DANIEL'),
  ('LUBEGA MICHEAL MALCOM'), ('LUTAAYA CATHERINE'), ('LWALANDA HAKIM'), ('LWASSA DALTON ELIJAH'),
  ('MAGALA DALTON EDWARD'), ('MAGUMBA SHAKIR'), ('MIGADDE SHAKUR SUCCESS'), ('MPAIRWE SERENE LYTON'),
  ('MUGERWA JERICHO'), ('MUKIIBI JONATHAN'), ('MUKISA FAVOR'), ('MUKISA FAVOUR'),
  ('MUKULU MAHAD NASSIB'), ('MUWAMBA WILFRED'), ('NABUKEERA SHUKRAN'), ('NAKABUYE CYNTHIA'),
  ('NAKALANZI PROMISE'), ('NAKASIISA SHEILLA KABOGGOZA'), ('NAKIBONEKA PRUDENCE'), ('NAKIGULI SHIVAN'),
  ('NAKITTO RHONEL RUTH'), ('NAMAGALA EDRON JOAN'), ('NAMBEJJA CHRISTINE'), ('NAMUBIRU AFRICA RACHEAL'),
  ('NAMUYIGA JOVIA'), ('NAMYALO TASHEEMIM'), ('NANJEGO VICTORIA'), ('NANKUBUGE SHAINAH'),
  ('NANNUNGI ANNA PRECIOUS'), ('NANTEZA LYAN'), ('NASASIRA DIVINE'), ('NASIMBWA CIARA NANA'),
  ('NASSIMBWA GRACE HANNAH'), ('NKWISANA REAGAN'), ('OLA KERON MICHELLE'), ('RASHMY WAHIDAH IMAN'),
  ('SEKATE GODFREY JUNIOR'), ('SSEBUUFU RAYMOND'), ('SSEKAJIGO VICTOR'), ('SSERUYANGE TIMOTHY'),
  ('SSIMBWA TALIQ'), ('TUMUSIIME FRANCIS'), ('TURYAKIRA TYRONE'), ('WAIKYA ISRAELLA PHOENIX'),
  ('WALUSIMBI JETHRO VALENTINE')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P4' AND s.name = 'EAGLETS' AND s.class_id = c.id;

-- P4 BUNNIES
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABAASA MELISA'), ('AGABA JOHN TREASURE'), ('AHUMUZA PRAISE ROBERT'), ('AINEMBABAZI GRACE REINAH'),
  ('AINEMBABAZI MELISA'), ('AKAMUTUHA JANET'), ('AKWERO LYN AUSTINE'), ('AMILAH ADAMS KYEYUNE'),
  ('ANVIKO SHANTAL MARION'), ('ARIIHO ISRAEL'), ('ARINDA MARTHA ELLONY'), ('ATUHAIRE GEORGIA ROSE'),
  ('BALIKUDDEMBE ELVIS'), ('BARUNGI VICTORIA'), ('BATANDA JETHRO'), ('BUYONDO ISRAEL'),
  ('ELOY TITUS SSENTONGO'), ('IRENE MALAIKA NABBAALE'), ('KABAGAMBE WEISSMAN'), ('KAKUNGULU RYAN MARK'),
  ('KALIBBALA AKRAM'), ('KALYANGO RAHEEM'), ('KATO JOVANS KABUYE'), ('KATUMBA CONRAD'),
  ('KATUMBA MARIA'), ('KAVUMA NORINE ESTHER'), ('KAWEESA KEIRAN'), ('KAWEESI HASHIM SSESSAAZI'),
  ('KIMBUGWE ABDALLAH'), ('KOMUJUNI FEDRACE'), ('KWEZI ROBINS'), ('MAGOMA BELICIA'),
  ('MALAIKA TRIXIE KIYAGA'), ('MIREMBE RAUDAH'), ('MUKIRIZA GEORGE MBOOWA'), ('MULUNGI ASABA JOANNAH'),
  ('MUSIIME GIFT'), ('MUYAMA ABIGAIL'), ('NABBONGOLE KATRINAH'), ('NABUKENYA JOSEPHINE KATE'),
  ('NAKALUNGI GABRIELLA IVANNAH'), ('NAKASUMBA ANITAH'), ('NALUBEGA MARIA'), ('NALUYANGE MADRINE DOROTHY'),
  ('NALWANGA JAZMINE'), ('NAMAGANDA BRIANNAH STEPHANIA'), ('NAMANDA MAJORIE'), ('NAMAZZI DESIRE HILDA'),
  ('NAMPIIMA PAULINE'), ('NAMUGERWA SABRINA'), ('NAMUJJUZI WINFRED'), ('NAMULI COMFORT'),
  ('NAMUTEBI LEONAH ROSELLA'), ('NANSUMBI DEBORAH KENDRA'), ('NANYUNJA RINAH NANA'), ('NASIRUMBI ISABELLA'),
  ('NDAGIRE SARAH'), ('NTAMBI REAGAN'), ('NYAKATO EDRINA'), ('SANYU NISHA GASARO'),
  ('SSEMPIJJA OSCAR'), ('SSEWANYANA AARON'), ('TAMALE JOHN FRANCIS'), ('TREASURE ELIZABETH SEKU'),
  ('TUKUNDANE EUGENE'), ('WALUSIMBI MARTIN'), ('WASSWA JONATHAN KABUYE'), ('WOSERO JOSHUA')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P4' AND s.name = 'BUNNIES' AND s.class_id = c.id;

-- P5 SKYHIGH
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AKOL LEON MASABA'), ('ASIIMWE MONICA'), ('ATUHAIRE ANGELLA'), ('BAKINDO SIMON SALA'),
  ('BANADDA HASHIM'), ('BUKIRWA RAHMA DDUMBA'), ('CHOL GAI ALIER NHIAL'), ('KAWULUKUSI SHAKURAN'),
  ('KAYAGA KATRINAH'), ('KEBIRUNGI DAISY EVE'), ('KIGGUNDU FAVOUR MARCUS'), ('KIGOZI RAHEEM'),
  ('KISAKYE MARTHA'), ('KWAGALA FAITH JOY'), ('LUMU ANNA GRACIOUS'), ('MATSIKO HANIF'),
  ('MAWEJJE UKASHA'), ('MBABAZI CYRON'), ('MBAZIIRA JOEL'), ('METALORO MARY PURITY'),
  ('MIKKA TYABA NICHOLAS'), ('MPANGA FAHAD'), ('MUBIRU INAN'), ('MUBIRU MIGUEL HERO'),
  ('MUKASA BRYTON'), ('MUKIIBI MICHEAL'), ('MULUMBA FAVOUR CLINTON'), ('MUTESASIRA JOLLENE'),
  ('MUTESI TRINA TEDDY'), ('NABAGEREKA CHRISTINE MELANIE'), ('NABAGULANYI TENDO TREASURE'), ('NAKAWOOYA TEACILAM MUYINGO'),
  ('NAKIBUUKA ASSUMPTA'), ('NAKIBUULE MELAN BLESSED'), ('NAKIGANDA LISA'), ('NAKITTO HAPPY DANIELLA'),
  ('NAMATOVU IMMACULATE'), ('NAMATOVU PROVIA ABIGAIL'), ('NAMATOVU SHUKRAN'), ('NAMAYANJA ANTONIO MERCY'),
  ('NAMULEMA MERCY ALLEN'), ('NAMULINDWA VICTORIA'), ('NAMUTALE FEDERICO'), ('NANTONGO SHANTEL'),
  ('NIMUKUNDA CYRUS MURAMIRA'), ('NSAMBA JORDAN RICH'), ('SSEJJUUKO PEDRO'), ('SSEKANJAKO ARAFAT'),
  ('SSETUMBA JESSIE'), ('TUSUBIRA ARTHUR'), ('WASSAJJA MELISSA RAY')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P5' AND s.name = 'SKYHIGH' AND s.class_id = c.id;

-- P5 SUNRISE
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ADAM SALAMA MOKHTAR'), ('AHEREZA HONOUR MULUNGI'), ('AINOMUGISHA ANGEL'), ('ALIYAH ADAMS KYEYUNE'),
  ('ASHABA ELIZABETH'), ('BAGONZA JOAB'), ('BLESSING SHILOH'), ('BUKIRWA SHILOH'),
  ('BUYUNGO BRANDON ERIC'), ('IRANYA MARCUS'), ('KAKONA JORDAN KASH'), ('KALULE CAESER CARLOS'),
  ('KASOZI AAMRAT'), ('KEMIGISHA ALEXANDRIA'), ('KIGGUNDU LUKE'), ('KISMART DAUDA'),
  ('LUBEGA MALCOM EMMANUEL'), ('LUGYA AKRAM'), ('LUYIGA RAYAN'), ('MANZI EVANS'),
  ('MUBEEZI SHADIA LUYIGA'), ('MUHUMUZA ADELITO'), ('MULANGIRA JOSEPH'), ('MULUNGI IAN'),
  ('MUYIZA SYRUS'), ('NABIRYE PRECIOUS'), ('NABUUMA VANESSA'), ('NAKAWEESI MICHELLE'),
  ('NAKUNGU PRECIOUS CYNTHIA'), ('NAMAGANDA IMRAH SSEMPIJJA'), ('NAMAKULA SOPHIA KITIIBWA'), ('NAMIREMBE ALPHA DDAMULIRA'),
  ('NAMUTEBI GETRUDE'), ('NAMWANJA JOHNBAPTIST'), ('NANJOBE VANESSA'), ('NANSUBUGA MANNUELLAH'),
  ('NANTONGO BUSHIRA'), ('NANUNGI DRUCILA LUTEETE'), ('NASSANGA MARIA VIENNA'), ('NICHOLAS ITAAGA TRUST'),
  ('NINSIIMA MARY SHALOM'), ('NVANUNGI SHANIEZ'), ('PHILLIP DAVID LUKANDWA'), ('RWOMUSHANA OMUGISHA GABRIEL'),
  ('SSEBABENGA KERON'), ('SSEMATIMBA MARK'), ('SSEMOMBWE ANDERSON'), ('SSENGENDO PRITA'),
  ('SSEWAKIRYANGA HOSEA'), ('SSUUNA RAFAN WASSAJJA'), ('TEMITOPE ABOSODE'), ('TENDO HASIFA HAKIM'),
  ('TWESIGE ADRIAN'), ('UWINEZA SHAMAH ZINDUKA')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P5' AND s.name = 'SUNRISE' AND s.class_id = c.id;

-- P5 SUNSET
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AINEBYONA ISAIAH'), ('ANKUNDA DENISE'), ('ANYANGO KAREN MERCY'), ('ASIIMWE SHEENA'),
  ('ATAMBA CAROL JIREH'), ('ATUKUNDA GRAMIA'), ('AYEBAREYESU EXCELLENT'), ('BWIRE CLARISSA SUCCESS'),
  ('DDUMBA FRANCIS'), ('GITTA RAZAQ'), ('HIPAINGAH SALAH JOSEPHINE'), ('INEZA PEACE DORIAN'),
  ('JIBE IMMACULATE'), ('KABUYAYA RAYANNA'), ('KAKANDE BLESSED'), ('KAMUGISHA NATALIE'),
  ('KATEREGGA RASHIM'), ('KATEREGGA RAUL'), ('KAVUMA LORINE GRACE'), ('KAYEMBA SHAN'),
  ('KHARUNDA ESTHER'), ('KIMBUGWE MELVIN ELISHA'), ('KIRABIRA ARNOLD'), ('KITANDWE ABDULSHARKUL'),
  ('KUTEESA ISMAIL KALULE'), ('LWANGA RAPHAEL NAMPAGI'), ('LYMIAH AVRIL SALIM'), ('MATENYITIA MERCY'),
  ('MICHORO ANNA ALEX'), ('MOYA ELISHA'), ('MUGISA VALENTE CURTIS'), ('MUKISA SAMSON'),
  ('MULINDWA EDDY'), ('MURAMUZI JAN_JENSEN'), ('NABAKOOZA CHRISTINE'), ('NABIKOLO ANNA'),
  ('NAJIB ALSHAFIQ'), ('NALUMANSI LYTON'), ('NAMALA SALASBEL'), ('NAMBI NAAVA'),
  ('NANDAWULA DESIRE'), ('NANONO ROSHAN ISMAIL'), ('NINSIIMA ALIANAH KIRABO'), ('NYONYOZI EDRINAH SKYLER'),
  ('SSEKANDI RAMADHAN'), ('SSONKO HENRY ARTHUR'), ('UMUTESI DINAH INEZ'), ('WALUSIMBI ABDUL SHARIK')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P5' AND s.name = 'SUNSET' AND s.class_id = c.id;

-- P6 RADIANT
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABAHO FARRELL'), ('AINEMBABAZI ELIANAH'), ('ARIHO CALVIN'), ('ATUHAIRE COMFORT'),
  ('ATUHAIRE PROMISE'), ('ATWIINE RUTH'), ('AYEBALE ABORIGINE'), ('BUKENYA SHADRACK'),
  ('ELIANA TREASURE MUKISA'), ('KABUYAYA TATIANA'), ('KAKOOZA JUMA KAGGWA'), ('KIDHUUBO PATRICIA GLADYS'),
  ('KIMBUGWE TIMOTHY'), ('KISAWUZI PROSPER JONATHAN'), ('KIWANA GENEROUS'), ('KIYAGA TERRY ELIJAH'),
  ('KIZITO ISAIAH'), ('LUBOWA SHANITAH'), ('MURUNGI SHAREEF RAUSHAN'), ('MUTANDA LEON ARTHUR'),
  ('MUWANGUZI JEREMIAH ANKUNDA'), ('NAJJINGO TEOPISTA KALUNGI'), ('NAKANDI ROCINTA'), ('NAKINTU RAMLAH'),
  ('NAKYANZI BENINA'), ('NAMATA DIVINE HANNAH'), ('NAMITALA TONNIA'), ('NAMUTEBI LETICIA'),
  ('NAMYALO CLARA KETRA'), ('NANKYA NUSRAH'), ('NSUBUGA ERON'), ('NSUBUGA MATILDA YULLIANA'),
  ('OMAR ROSHEEN NSEGIMAANA'), ('PARA PATRINA'), ('RUGUMAYO JOSEPH REMIGIUS'), ('SANGA FAITH LISA'),
  ('SSEKATAWA CLANCY CALVIN'), ('SSENYONJO SEAN ADRIAN'), ('TALIDDA SARAH'), ('WALUGEMBE JONATHAN'),
  ('WAMALA CHESTNUT'), ('YIGA INNOCENT')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P6' AND s.name = 'RADIANT' AND s.class_id = c.id;

-- P6 VIBRANT
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ADITE DIRAN'), ('AKATUSIIMA RAVEN'), ('ANZOA JOVANNAH'), ('ATURINDA KELTON'),
  ('BALUKU ELEUTHERIUS BROGAN'), ('BUGINGO JORAM'), ('ITUNGO ISOBEL AYETA'), ('KABISWA ISAAC'),
  ('KALUNGI DAVID'), ('KATUMBA MARTHA'), ('KIRABO MADRINE PRINCESS'), ('KIWENDO CALVIN'),
  ('KYOMUGISHA ETHEL HANNAH'), ('LUYIGA RAHIM'), ('MAYITTO CHRISTIAN'), ('MIREMBE GIFT REBECCA'),
  ('MIRIMU ELIJAH'), ('MUBARAH RANIAH YAIZD'), ('MUGARURA PAXTON'), ('MUGENYI RYAN'),
  ('MUKIIBI JOSEPH'), ('MUKISA SHAMMAH'), ('MURUNGI AARON'), ('MUSIIMENTA HANNAH AMITO'),
  ('MUTEBI JORDAN DIEGO'), ('MUWANGUZI ETHAN'), ('NABACHWA SHIVAN'), ('NABUKENYA TYRA'),
  ('NAJJINGO RHONITAH LUCY'), ('NAKAWUKI RIANAH'), ('NAKAYENGA MARY KATEREGGA'), ('NAKIBUULE SHEENAH'),
  ('NAKIJJE PRISCA RESTY'), ('NAKIMERA MARIA'), ('NAKIMULI KATRINAH PEACE'), ('NAMAGANDA LUISA JOY'),
  ('NAMMANDA HAIFA'), ('NANGENDO GABRIELLA'), ('NANSAMBA ESTHER'), ('NANSUBUGA ASIA'),
  ('NASSAAZI JACINTA KIZZA'), ('NATYABA EVELYN TENDO'), ('NAYIGA SHUDAT ZAHARA'), ('OSINDE AHMED'),
  ('SSAAZI RAPHEAL'), ('SSENDAGI SOLOMON'), ('SSENUNGI TITUS')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P6' AND s.name = 'VIBRANT' AND s.class_id = c.id;

-- P6 VICTORS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AMUGE LYNDSEY MILES'), ('ATIM ZUBEDA'), ('ATULINDA AISHA'), ('AYEBARE MELLISA'),
  ('BATARINGAYA SHIMARO'), ('BUKIRWA SHAMRA DDUMBA'), ('BULEGA PIUS'), ('JJAGWE JOVAN'),
  ('JJUMBA ANGELLO'), ('KAJJUMBA BELLA COLYTE'), ('KAREMERA ABDUL HANAN'), ('KATONO ALLAN'),
  ('KAZIBA JOSHUA'), ('KIGGUNDU LIA'), ('KIRABO EVAS'), ('KIZZA JOYCE MYER SEMPA'),
  ('KYALIGONZA HARVEY RENATAH'), ('LUBWAMA MARTIN WASSWA'), ('LUKWAGO LUCKY AHMET'), ('LUKWAGO SHAWN'),
  ('LUYIMBAZI RODNEY'), ('LWANGA WYCLIFF'), ('MAKIKA MEEKSON'), ('MUBIRU RAJAB'),
  ('MUKISA PHILEMON'), ('MULWANA JONATHAN'), ('MUSASIZI ADRIAN'), ('MWEBAZA PEACE'),
  ('NABWIRE GLORIA MICHELLE'), ('NAGAWA ANTHONIA BEATRICE'), ('NAKABUYE SHAROM'), ('NAKITTO MYRA REMEDY'),
  ('NAKITTO SHIFURAH ECMAT'), ('NALUBEGA JANIPHER'), ('NAMARA REBECCA BLESSED'), ('NAMAWEJJE ELIZABETH SHANTAL'),
  ('NAMIREMBE KAHLAN MARTHA'), ('NAMPIJJA PATRICIA'), ('NAMUGENYI HELLEN'), ('NAMUSISI MARIA FEDERESI'),
  ('NAMWANJE MACRINAH'), ('NASSUNA EMILLY MATINAH'), ('NASSUUNA WILDER'), ('NAYIGA JOSELINE MARINA'),
  ('NYAKATO EDRINAH'), ('NYIRANEZA VIVIAN'), ('SSEMAKULA EZRA'), ('SSERUNKUMA ABRIELLE PROSPER'),
  ('TUKUNDANE EAMON'), ('YEBETE MARY SADAD ELIAS')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P6' AND s.name = 'VICTORS' AND s.class_id = c.id;

-- P7 ACHIEVERS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ALINDA MARIA FORTUNATE'), ('ASIIMWE DIVINE MERCY'), ('AYEBAZIBWE EDNAS'), ('BATARINGAYA COLLINS'),
  ('HAIRAT DAUDA'), ('KABAGAMBE RIVEINS BLAQ'), ('KARUNGI MELISSA OPRAH'), ('KASUMBA MARIAM ANGEL'),
  ('KATAMBALA ROMAN SOLOMON'), ('KIRABIRA GODFREY ALVIN'), ('KITAYIMBWA STANISLAUS PROSPER'), ('KITENGEJJA PRISCILLA'),
  ('KIYIMBA MARIAM'), ('KUKIRIZA JOSHUA'), ('KYAGABA DAVID TAYLOR'), ('KYAGABA JEREMIAH'),
  ('LUTEMBE RIAZ'), ('MASIKA SEANICE ASINGYA'), ('MBAZIIRA TIHAN'), ('MIREMBE ESTHER ANDREA AIDAH'),
  ('MUKWAYA MELVINAH MICHEELE EDITH'), ('MUSASIZI PHILP DAVIS'), ('MUTEBI IMRAN MUBIRU'), ('MUWANGUZI SUHAIR'),
  ('NABATEREGGA JOSELYN KIRABO'), ('NAGGAYI NATAVIAH'), ('NAJJEMBA ANNABELLE LUCY'), ('NAKABUYE ESTHER MARITEZ'),
  ('NAKATO MARY'), ('NAMATOVU JOSELINE MERCY'), ('NAMPIJJA JANE')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P7' AND s.name = 'ACHIEVERS' AND s.class_id = c.id;

-- P7 SUCCESS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('AGAWO HARMONY ASAHEL'), ('AINOMUGISHA JOY ATUBASIISE'), ('AMUGE TEMPLE'), ('ANKUNDA CEDRIC MURAMIRA'),
  ('ATUHAIRWE ALVIN'), ('ATURINDA KAREN'), ('BYARUHANGA HUSSEIN LEFA'), ('JJENGO MUSTAPHA JUMA'),
  ('KAFEERO FELIX'), ('KASOZI VERNICE CHRISTABELLE'), ('KATUSIIME SHIVAN KAIJA'), ('KIRISA JOEL JAYSON'),
  ('KISIRA JORAM'), ('LUTAAYA JOHN WILSON'), ('MUBIRU RAYAN KIZITO'), ('MUGAGGA JESSICAH NAKALEMA'),
  ('MUHUMUZA NEWMAN'), ('NAKABALIRA MANGDALENE NAKALEMBE'), ('NAKATO THERESA SEMPA'), ('NAKAYONDE MARIA'),
  ('NAKIBUULE AMINAH'), ('NAKIMULI MARIA IVY'), ('NAKINTU DANIELLA'), ('NAKYAMBADDE HENRIATAH SHEILAH'),
  ('NAKYANZI COTRIDA MARIA KIARA'), ('NALUBEGA SHAMIRAH KASOZI'), ('NAMATOVU RACHEAL'), ('NAMUGENYI MELISSA'),
  ('NANTABA PATRICIA'), ('NSANZINTWARI TREASURE MARY'), ('NTONGO GLORIA'), ('NUWAMANYA WILSON'),
  ('NUWASIIMA ANNABEL'), ('OKIA JORDAN DARENS'), ('OKOTEL BARUCH'), ('SSALI RAHIM'),
  ('SSERUNJOGI JOHNMARK'), ('TALEMWA KAGGWA VIANNEY GODROCK'), ('WASSWA JEREMIAH SEMPA'), ('WERE KELLY EDWARD'),
  ('WESONGA ALBERT MULUNGI')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P7' AND s.name = 'SUCCESS' AND s.class_id = c.id;

-- P7 WINNERS
INSERT INTO public.students (name, class_id, stream_id)
SELECT student_name, c.id, s.id
FROM (VALUES 
  ('ABALINABYO NATASHA'), ('AGABA REAGAN'), ('AHIMBISIBWE MARKSON'), ('AHURIRA CALEB'),
  ('APOLOT HELLEN GRACE'), ('AUDO TRACY'), ('AYERANGO GLORIA'), ('BAGUMA JOSHUA JASON'),
  ('BESIGYE KEVIN'), ('BYARUHANGA HASSAN KGOTSO'), ('KAKEETO BENJAMIN BENEDICTO'), ('KAKOOZA SHURAIM MWESEZI'),
  ('KALYANGO JONATHAN'), ('KATO JOSEPH ENOCK'), ('KAWADWA COLLINS'), ('KEMIGISHA PRINCESS'),
  ('KUTOSI FAITH HANNAH'), ('LUKYAMUZI IVAN'), ('MAGUMBA SHAKUR'), ('MUBUYA RYAN'),
  ('MUHANGUZI LINCOLN'), ('MUHINDO PATRICK PEDIAH'), ('MUKAMA CALVIN'), ('MULINDWA TRAVIS KASOZI'),
  ('MULUMBA ROBINSON'), ('MUTEESA JOHNBAPTIST TALIIKA'), ('MUTIIBWA MELLISA'), ('NABWIRE MARIA MERCILINA'),
  ('NAKAWEESA NICOLE KELVIN'), ('NAKAYENGA FLAVIA'), ('NAKAYONGO PATRICIA BEST'), ('NAKIMBUGWE ELETHERIA'),
  ('NAKKU SAMANTHA HAZEL'), ('NAMUDDE VANESSA'), ('NANTEZA MARJORINE'), ('NANZIRA MARY IVY'),
  ('NASSUNA HARIANAH KATRINAH'), ('NATOORO SHARITAH KAKOOZA'), ('RUBANGAKENE GABRIEL'), ('SSEMATIMBA ERNEST'),
  ('SSEMPA RYAN TERRY'), ('SSENYONGA JOHNBOSCO'), ('SSERUNJOGI SIMON ALVIN'), ('WASSWA JOHN ELIJAH'),
  ('ZZIWA ANDREW GERALD')
) AS t(student_name)
CROSS JOIN public.classes c
CROSS JOIN public.streams s
WHERE c.name = 'P7' AND s.name = 'WINNERS' AND s.class_id = c.id;