-- Delete existing P4-CUBS students
DELETE FROM students WHERE class_id = 'P4' AND stream_id = 'CUBS';

-- Insert corrected P4-CUBS students with proper names and photo URLs
INSERT INTO students (id, name, email, class_id, stream_id, photo_url, is_verified, created_at) VALUES
('P4-CUBS-001', 'AGABA JOSHUA WALTER', 'agabajoshua@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/AGABA JOSHUA WALTER.JPG', false, now()),
('P4-CUBS-002', 'AINOMUGISHA PETRINAH', 'ainomugishapetrinah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/AINOMUGISHA PETRINAH.JPG', false, now()),
('P4-CUBS-003', 'AKATUHEREZA WILLISHA MERRICK', 'akatuherzawillisha@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/AKATUHEREZA WILLISHA MERRICK.JPG', false, now()),
('P4-CUBS-004', 'AMPUMUZA ELIANAH', 'ampumuzaelianah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/AMPUMUZA ELIANAH.JPG', false, now()),
('P4-CUBS-005', 'ARINITWE CLEIN', 'arinitwe@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ARINITWE CLEIN.JPG', false, now()),
('P4-CUBS-006', 'ASIIMWE DERRICK RUJOKI', 'asiimwederrick@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ASIIMWE DERRICK RUJOKI.JPG', false, now()),
('P4-CUBS-007', 'ASINGUZA BRENDA', 'asinguzabrenda@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ASINGUZA BRENDA.JPG', false, now()),
('P4-CUBS-008', 'ATWIINE JOTHAM', 'atwiine@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ATWIINE JOTHAM.JPG', false, now()),
('P4-CUBS-009', 'BATANDA DYLAN', 'batandadylan@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/BATANDA DYLAN.JPG', false, now()),
('P4-CUBS-010', 'BUWEMBO NEYMAR JUNIOR', 'buwemboneymar@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/BUWEMBO NEYMAR JUNIOR.JPG', false, now()),
('P4-CUBS-011', 'BYAMUKAMA KEITH', 'byamukamakeit@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/BYAMUKAMA KEITH.JPG', false, now()),
('P4-CUBS-012', 'HANNAH FRIEND KIZITO', 'hannahfriend@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/HANNAH FRIEND KIZITO.JPG', false, now()),
('P4-CUBS-013', 'ISHIMWE QUEEN NGABIRE', 'ishimwequeen@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ISHIMWE QUEEN NGABIRE.JPG', false, now()),
('P4-CUBS-014', 'ISIKOT VERON JOY', 'isikotveron@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/ISIKOT VERON JOY.JPG', false, now()),
('P4-CUBS-015', 'JAKIRA FLAVOUR ROBIN', 'jakiraflavour@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/JAKIRA FLAVOUR ROBIN.JPG', false, now()),
('P4-CUBS-016', 'KARUNGI NEIRAH', 'karungineirah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KARUNGI NEIRAH.JPG', false, now()),
('P4-CUBS-017', 'KASULE ELSEN ZAWADI', 'kasuleelsen@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KASULE ELSEN ZAWADI.JPG', false, now()),
('P4-CUBS-018', 'KATUNDA DARREN', 'katundadarren@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KATUNDA DARREN.JPG', false, now()),
('P4-CUBS-019', 'KAWUKI GIPSON', 'kawukigipson@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KAWUKI GIPSON.JPG', false, now()),
('P4-CUBS-020', 'KAYONGO HYRAT NAMBALIRWA', 'kayongohyrat@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KAYONGO HYRAT NAMBALIRWA.JPG', false, now()),
('P4-CUBS-021', 'KIBUDDE MICHEAL', 'kibuddemicheal@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KIBUDDE MICHEAL.JPG', false, now()),
('P4-CUBS-022', 'KIMBUGWE STEWART', 'kimbugwestewart@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KIMBUGWE STEWART.JPG', false, now()),
('P4-CUBS-023', 'KIMERA JONATHAN', 'kimerajonathan@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KIMERA JONATHAN.JPG', false, now()),
('P4-CUBS-024', 'KISENYI MAGGIE MELLISA', 'kisenyimaggie@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KISENYI MAGGIE MELLISA.JPG', false, now()),
('P4-CUBS-025', 'KITENDA ALMAH ZURI', 'kitendaalmah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KITENDA ALMAH ZURI.JPG', false, now()),
('P4-CUBS-026', 'KOBUSINGE MARIANAH NATAL', 'kobusingemarianah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KOBUSINGE MARIANAH NATAL.JPG', false, now()),
('P4-CUBS-027', 'KYALIGONZA JOSEPHINE TUSIIME', 'kyaligonzajosephine@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KYALIGONZA JOSEPHINE TUSIIME.JPG', false, now()),
('P4-CUBS-028', 'KYENYINE COSSILINE', 'kyenyinecossiline@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KYENYINE COSSILINE.JPG', false, now()),
('P4-CUBS-029', 'KYOMUHENDO GRACE KIBIRIGE', 'kyomuhendograce@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/KYOMUHENDO GRACE KIBIRIGE.JPG', false, now()),
('P4-CUBS-030', 'LUBOWA ABUBAKER', 'lubowaabubaker@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/LUBOWA ABUBAKER.JPG', false, now()),
('P4-CUBS-031', 'LUKWAGO RAYAN', 'lukwagorayan@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/LUKWAGO RAYAN.JPG', false, now()),
('P4-CUBS-032', 'LUMU ANGEL FAVOUR', 'lumuangel@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/LUMU ANGEL FAVOUR.JPG', false, now()),
('P4-CUBS-033', 'MAGOMA CHARLES BENHUR', 'magomacharles@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MAGOMA CHARLES BENHUR.JPG', false, now()),
('P4-CUBS-034', 'MAYANJA VUUBI', 'mayanjavuubi@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MAYANJA VUUBI.JPG', false, now()),
('P4-CUBS-035', 'MUBINZI MOSES', 'mubinzimoses@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MUBINZI MOSES.JPG', false, now()),
('P4-CUBS-036', 'MUGABI JOSH MICHEAL', 'mugabijosh@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MUGABI JOSH MICHEAL.JPG', false, now()),
('P4-CUBS-037', 'MUNEZERO BLESSEN', 'munezeroblessen@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MUNEZERO BLESSEN.JPG', false, now()),
('P4-CUBS-038', 'MWIMA RAIHAN', 'mwimaraihan@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/MWIMA RAIHAN.JPG', false, now()),
('P4-CUBS-039', 'NAKANWAGI KEIRAH', 'nakanwagikeirah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAKANWAGI KEIRAH.JPG', false, now()),
('P4-CUBS-040', 'NAKISIGE PRECIOUS SHALOM', 'nakisigeprecious@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAKISIGE PRECIOUS SHALOM.JPG', false, now()),
('P4-CUBS-041', 'NALUGO PRECIOUS CHLOE', 'nalugoprecious@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NALUGO PRECIOUS CHLOE.JPG', false, now()),
('P4-CUBS-042', 'NAMBALIRWA TRUDE ABIGAIL', 'nambalirwatrude@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAMBALIRWA TRUDE ABIGAIL.JPG', false, now()),
('P4-CUBS-043', 'NAMUBIRU REGINA MULASANGEYE', 'namubiruregina@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAMUBIRU REGINA MULASANGEYE.JPG', false, now()),
('P4-CUBS-044', 'NAMUMBEJJA RYHAN', 'namumbejjaryhan@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAMUMBEJJA RYHAN.JPG', false, now()),
('P4-CUBS-045', 'NAMUYANJA CARLTON NAKAWUNGU', 'namuyanjacarlton@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAMUYANJA CARLTON NAKAWUNGU.JPG', false, now()),
('P4-CUBS-046', 'NANSUBUGA TRACY CAMILLA', 'nansubugatracy@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NANSUBUGA TRACY CAMILLA.JPG', false, now()),
('P4-CUBS-047', 'NANYONGA ZIADAH LUYIGA', 'nanyongaziadah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NANYONGA ZIADAH LUYIGA.JPG', false, now()),
('P4-CUBS-048', 'NANYONJO AGNES', 'nanyonjoagnes@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NANYONJO AGNES.JPG', false, now()),
('P4-CUBS-049', 'NANYONJO PATIENCE', 'nanyonjopatience@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NANYONJO PATIENCE.JPG', false, now()),
('P4-CUBS-050', 'NASSIWA HAILEY ULRIKA', 'nassiwahailey@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NASSIWA HAILEY ULRIKA.JPG', false, now()),
('P4-CUBS-051', 'NATASHA ESTHER OKALLO', 'natashaesther@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NATASHA ESTHER OKALLO.JPG', false, now()),
('P4-CUBS-052', 'NAYEBARE TIMOTHY', 'nayebaretimothy@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NAYEBARE TIMOTHY.JPG', false, now()),
('P4-CUBS-053', 'NGELESE HOSANAH VALERIA', 'ngelesehosanah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NGELESE HOSANAH VALERIA.JPG', false, now()),
('P4-CUBS-054', 'NIYIBIZI JERUSA', 'niyibizijerusa@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NIYIBIZI JERUSA.JPG', false, now()),
('P4-CUBS-055', 'NKIMULI ETHEL GRACE', 'nkimuliet@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NKIMULI ETHEL GRACE.JPG', false, now()),
('P4-CUBS-056', 'NSIIMIRE FAITH', 'nsiimirefaith@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NSIIMIRE FAITH.JPG', false, now()),
('P4-CUBS-057', 'NSUBUGA MICHEAL JORDAN', 'nsubugamicheal@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/NSUBUGA MICHEAL JORDAN.JPG', false, now()),
('P4-CUBS-058', 'SEKATE NOELLA', 'sekatenoella@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SEKATE NOELLA.JPG', false, now()),
('P4-CUBS-059', 'SSALI MICHEAL', 'ssalimicheal@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSALI MICHEAL.JPG', false, now()),
('P4-CUBS-060', 'SSEKAJJA NASHIFU', 'ssekajanashifu@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSEKAJJA NASHIFU.JPG', false, now()),
('P4-CUBS-061', 'SSENDYOSE CYRUS FRANKLIN', 'ssendyosecyrus@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSENDYOSE CYRUS FRANKLIN.JPG', false, now()),
('P4-CUBS-062', 'SSENKAAYI EVERISTO NILL', 'ssenkaayieveristo@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSENKAAYI EVERISTO NILL.JPG', false, now()),
('P4-CUBS-063', 'SSENYONGA JEREMIAH', 'ssenyongajeremiah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSENYONGA JEREMIAH.JPG', false, now()),
('P4-CUBS-064', 'SSENYONJO MERCY', 'ssenyonjomercy@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSENYONJO MERCY.JPG', false, now()),
('P4-CUBS-065', 'SSEREMBA JEREMIAH', 'sserembajeremiah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSEREMBA JEREMIAH.JPG', false, now()),
('P4-CUBS-066', 'SSERUMAGA PUTIN TREVIS', 'sserumagaputin@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/SSERUMAGA PUTIN TREVIS.JPG', false, now()),
('P4-CUBS-067', 'WANYENZE MARIANAH TATIANAH', 'wanyenzemarianah@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/WANYENZE MARIANAH TATIANAH.JPG', false, now()),
('P4-CUBS-068', 'YIGA SEBASTIAN TRAVIS', 'yigasebastian@glorious.com', 'P4', 'CUBS', 'https://fresh-teacher.github.io/gloriouschool/YIGA SEBASTIAN TRAVIS.JPG', false, now());