-- Delete the incorrectly created students first
DELETE FROM students WHERE class_id = 'P4' AND stream_id = 'P4-CUBS';

-- Insert 54 CUBS students for P4 class with correct email pattern (first two names only)
INSERT INTO students (id, name, email, default_password, class_id, stream_id, created_at) VALUES
(gen_random_uuid(), 'NDUMWAMI SOLOMON', 'ndumwamisolomon@glorious.com', '1001', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NANYONJO PATIENCE', 'nanyonjopatience@glorious.com', '1002', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'MUNEZERO BLESSEN', 'munezeroblessen@glorious.com', '1003', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'AMPUMUZA ELIANAH', 'ampumuzaelianah@glorious.com', '1004', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KIBUDDE MICHEAL', 'kibuddemicheal@glorious.com', '1005', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'HANNAH KIZITO FRIEND', 'hannahkizito@glorious.com', '1006', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NALUGO CHLOE PRECIOUS', 'nalugochloe@glorious.com', '1007', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'ASIIMWE RUJOKI DERRICK', 'asiimwerujoki@glorious.com', '1008', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMUYANJA NAKAWUNGU CARLTON', 'namuyanjanakawungu@glorious.com', '1009', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'LUMU FAVOUR ANGEL', 'lumufavour@glorious.com', '1010', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KYALIGONZA TUSIME JOSEPHINE', 'kyaligonzatusime@glorious.com', '1011', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KISENYI MAGGIE MELLISA', 'kisenyimaggie@glorious.com', '1012', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KIMBUGWE STEWART', 'kimbugwestewart@glorious.com', '1013', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KAYONGO NAMBALIRWA HYRAT', 'kayongonambalirwa@glorious.com', '1014', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAKIMULI GRACE ETHEL', 'nakimuligrace@glorious.com', '1015', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSENKAAYI NILL EVERISTO', 'ssenkaayinill@glorious.com', '1016', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'AGABA WALTER JOHN', 'agabawalter@glorious.com', '1017', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'JAKIRA FLAVOUR ROBIN', 'jakiraflavour@glorious.com', '1018', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KITENDA ZURI ALMAH', 'kitendazuri@glorious.com', '1019', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NSUBUGA JORDAN MICHEAL', 'nsubugajordan@glorious.com', '1020', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NANYONGA LUYIGA ZIADAH', 'nanyongaluyiga@glorious.com', '1021', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KAWUKI GIPSON', 'kawukigipson@glorious.com', '1022', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSALI MICHEAL', 'ssalimicheal@glorious.com', '1023', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSENDYOSE CYRUS FRANKLIN', 'ssendyosecyrus@glorious.com', '1024', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'BYAMUKAMA KEITH', 'byamukamakeith@glorious.com', '1025', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'WANYENZE MARIANAH TATIANAH', 'wanyenzemarianah@glorious.com', '1026', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMUBIRU MULASANGEYE REGINA', 'namubirumulasangeye@glorious.com', '1027', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'LUGENDO AMOS', 'lugendoamos@glorious.com', '1028', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMIREMBE NICOLE MARIA', 'namirembenicole@glorious.com', '1029', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NGELESE HOSANAH VALERIA', 'ngelesehosanah@glorious.com', '1030', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NATASHA OKALLO ESTHER', 'natashaokallo@glorious.com', '1031', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'YIGA SEBASTIAN TRAVIS', 'yigasebastian@glorious.com', '1032', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NASSIWA HAILEY ULRIKA', 'nassiwahailey@glorious.com', '1033', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KIMERA JONATHAN', 'kimerajonathan@glorious.com', '1034', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSENYONJO MERCY', 'ssenyonjomercy@glorious.com', '1035', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMBALIRWA TRUDE ABIGAIL', 'nambalirwatrude@glorious.com', '1036', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NSIIMIRE FAITH', 'nsimirefaith@glorious.com', '1037', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAKANWAGI KEIRAH', 'nakanwagikeirah@glorious.com', '1038', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMAASA MUKIRYA AMRON', 'namaasamukirya@glorious.com', '1039', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSEREMBA JEREMIAH', 'sserembajeremiah@glorious.com', '1040', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'ATWIINE JOTHAM', 'atwiinejotham@glorious.com', '1041', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'MAGOMA CHARLES BENHUR', 'magomacharles@glorious.com', '1042', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAMUMBEJJA RYHAN', 'namumbejjaryhan@glorious.com', '1043', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'ASINGUZA BRENDA', 'asinguzabrenda@glorious.com', '1044', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'SSENYONGA JEREMIAH', 'ssenyongajeremiah@glorious.com', '1045', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KOBUSINGE MARIANAH NATAL', 'kobusingemarianaḥ@glorious.com', '1046', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'NAYEBARE TIMOTHY', 'nayebaretimothy@glorious.com', '1047', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KASULE ZAWADIELSEN E', 'kasulezawadielsen@glorious.com', '1048', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'ATUHIRE JOSEPHINE', 'atuhirejosephine@glorious.com', '1049', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'MWIMA RAIHAN', 'mwimaraihan@glorious.com', '1050', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'LUKWAGO RAYAN F', 'lukwagorayan@glorious.com', '1051', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'KARUNGI NEIRAH IN', 'karungineirah@glorious.com', '1052', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'BATANDA DYLAN', 'batandadylan@glorious.com', '1053', 'P4', 'P4-CUBS', now()),
(gen_random_uuid(), 'LUBOWA ABUBAKER', 'lubowaabubaker@glorious.com', '1054', 'P4', 'P4-CUBS', now());