// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvipnmxnfqpshmknypzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12aXBubXhuZnFwc2hta255cHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MTYzNjgsImV4cCI6MjA3NzA5MjM2OH0.JKiwF8j5MMo6vZamI6cVUBLxM_BigI1ghYXkIcUoFxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});